sudo: false

language: java
jdk: oraclejdk11
dist: trusty

install: true
script:
  - cd book-shop-be
  - mvn clean test
  - cd ../book-warehouse-be
  - mvn clean test

branches:
  only:
    - master
    - development
