version: '3.5'

networks:
  books-network:

volumes:
  mysql-data:

services:

  mysqlbd:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 5442:5442
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  book-warehouse:
    container_name: book-warehouse
    build: ./book-warehouse/
    ports:
      - 8082:8082
    environment:
    depends_on:
      - mysqlbd
    networks:
      books-network