version: '3.5'

networks:
  books-network:

volumes:
  mysql-data:

services:

  mysqlbd:
    container_name: mysql
    image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 3626:3626

  book-warehouse:
    container_name: book-warehouse
    build: ./book-warehouse/
    ports:
    - 8082:8082
    environment:
    depends_on:
      - mysqlbd
    networks:
      books-network