version: '3.5'

#networks:
#  books-network:
#
#volumes:
#  mysql-data:

services:

  mysqldb:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  book-warehouse:
    container_name: book-warehouse
    build: ./book-warehouse/
    ports:
      - 8082:8082
#    environment:
    depends_on:
      - mysqldb
#    networks:
#      books-network