server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE}

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG